### ISSUE TITLE
validate functions raise deprecation warnings

### ISSUE THREAD

**Issue by carthik** [trlinkin/puppet-domain_membership#14]
PS C:\puppetcode\modules\win_essentials\manifests> puppet apply ..\examples\domain.pp --noop
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There i
s further documentation for validate_legacy function in the README.
   (at C:/puppetcode/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is
further documentation for validate_legacy function in the README.
   (at C:/puppetcode/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further doc
umentation for validate_legacy function in the README.
   (at C:/puppetcode/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
Notice: Compiled catalog for instructor.puppetlabs.vm in environment production in 0.56 seconds
Notice: /Stage[main]/Domain_membership/Exec[join_domain]/returns: current_value notrun, should be 0 (noop)
Notice: /Stage[main]/Domain_membership/Exec[reset_computer_trust]/returns: current_value notrun, should be 0 (noop)
Notice: /Stage[main]/Domain_membership/Reboot[after]: Would have triggered 'refresh' from 1 events
Notice: Class[Domain_membership]: Would have triggered 'refresh' from 3 events
Notice: /Stage[main]/Win_essentials::Domain/Reboot[after joining domain]: Would have triggered 'refresh' from 1 events
Notice: Class[Win_essentials::Domain]: Would have triggered 'refresh' from 1 events
Notice: Stage[main]: Would have triggered 'refresh' from 2 events
Notice: Applied catalog in 3.70 seconds

**Comment by trlinkin** [comment]
Yes, time for an overhaul.
